services:

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  django-web:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    volumes:
      - ./backend:/code

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - django-web
    env_file:
      - .env
    volumes:
      - /code/node_modules/
      - './frontend:/code'

volumes:
   postgres_data: