# Generated by Django 5.2.1 on 2025-05-12 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='startDate',
        ),
    ]
