# Generated by Django 5.2.1 on 2025-05-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolios', '0002_remove_portfolio_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='startTotalValue',
            field=models.FloatField(default=1000000000),
        ),
    ]
