# Generated by Django 5.2 on 2025-05-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolios', '0003_portfolio_starttotalvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trading',
            old_name='price',
            new_name='quantityOfTrading',
        ),
    ]
